apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: streaming

  template:
    metadata:
      labels:
        app: streaming

    spec:
      containers:
      - name: streaming

        image: {{ .Values.images.streaming }}

        ports:
        - containerPort: 3002

        env:
        - name: PORT
          value: "3002"

        - name: MONGO_URI
          value: "{{ .Values.mongo.uri }}"

        - name: JWT_SECRET
          value: "{{ .Values.jwtSecret }}"
---
apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: streaming

  ports:
  - port: 3002
    targetPort: 3002
